=== joshpitts-okta/developer/interfaceRepository/config/etc/opt/enc/ttc/common/schema/ttc/config/ttc.config.xsd
<xs:schema xmlns="http://emit-networking.org/schema/ttc/config" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://emit-networking.org/schema/ttc/config" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:simpleType name="i18n">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="objectId-type">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="class-type">
		<xs:all>
			<xs:element name="resource" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="params" type="params-type" minOccurs="0" maxOccurs="1"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="params-type">
		<xs:sequence>
			<xs:element name="param" type="param-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="param-type" mixed="true">
		<xs:all>
			<xs:element name="param" type="i18n" minOccurs="0" maxOccurs="1"/>
		</xs:all>
		<xs:attribute name="name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="references-type">
		<xs:sequence>
			<xs:element name="service" type="reference-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="reference-type">
		<xs:attribute name="include" type="xs:int"/>
		<xs:attribute name="exclude" type="xs:int"/>
		<xs:attribute name="type" type="reference-flavor-type"/>
		<xs:attribute name="ref" type="xs:int"/>
		<!-- if include/exclude are used they need to be exclusive required -->
		<!-- if type is used, both type and ref are required -->
	</xs:complexType>
	<xs:simpleType name="reference-flavor-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="include"/>
			<xs:enumeration value="exclude"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="credential-list-type">
		<xs:sequence>
			<xs:element name="credential" type="credential-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="credential-type">
		<xs:all/>
		<xs:attribute name="ref" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="nodes-type">
		<xs:sequence>
			<xs:element name="node" type="node-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="node-type">
		<xs:all>
			<xs:element name="name" type="i18n" minOccurs="0" maxOccurs="1"/>
			<xs:element name="address" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="services" type="references-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="servers" type="server-ref-list-type" minOccurs="0" maxOccurs="1"/>
		</xs:all>
		<xs:attribute name="type" type="node-flavor-type"/>
		<xs:attribute name="as-id" type="xs:byte"/>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:simpleType name="node-flavor-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CONNECTION_TIER"/>
			<xs:enumeration value="SERVICE_TIER"/>
			<xs:enumeration value="AUTHENTICATION_TIER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="log-level-flavor-type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="error"/>
			<xs:enumeration value="warn"/>
			<xs:enumeration value="info"/>
			<xs:enumeration value="debug"/>
			<xs:enumeration value="trace"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="logging-type">
		<xs:attribute name="level" type="log-level-flavor-type" default="info"/>
	</xs:complexType>
	<xs:complexType name="logging-handlers-type">
		<xs:sequence>
			<xs:element name="handler" type="class-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="server-list-type">
		<xs:sequence>
			<xs:element name="datagram" type="ipserver-type" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="stream" type="ipserver-type" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="hub" type="hub-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="server-type">
		<xs:sequence>
			<xs:element name="name" type="i18n" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="ipserver-type">
		<xs:complexContent>
			<xs:extension base="server-type">
				<xs:sequence>
					<xs:element name="max-connections" type="xs:int" default="10" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="hub-type">
		<xs:complexContent>
			<xs:extension base="server-type">
				<xs:sequence>
					<xs:element name="address" type="xs:string" minOccurs="1" maxOccurs="1"/>
					<xs:element name="domain-id" type="objectId-type" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
				<xs:attribute name="related-server" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="server-ref-list-type">
		<xs:sequence>
			<xs:element name="server" type="server-ref-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="server-ref-type">
		<xs:attribute name="ref" type="xs:int" use="required"/>
		<xs:attribute name="address" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="services-type">
		<xs:sequence>
			<xs:element name="service" type="service-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="service-type">
		<xs:all>
			<xs:element name="name" type="i18n" minOccurs="1" maxOccurs="1"/>
			<xs:element name="archive" type="xs:string" default="/opt/enc/ttc/services/lib" minOccurs="0" maxOccurs="1"/>
			<xs:element name="class" type="class-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="domain-id" type="objectId-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="logging" type="logging-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="auth-id" type="objectId-type" minOccurs="0" maxOccurs="1"/>
		</xs:all>
		<xs:attribute name="init" type="xs:boolean" default="true"/>
		<xs:attribute name="start" type="xs:boolean" default="true"/>
		<xs:attribute name="management" type="xs:boolean" default="false"/>
		<xs:attribute name="tunneling" type="xs:boolean" default="false"/>
		<xs:attribute name="logging-handler" type="xs:int"/>
		<xs:attribute name="id" type="xs:int"/>
		<xs:attribute name="threadpool" type="xs:int" default="2"/>
	</xs:complexType>
	<xs:complexType name="auth-platforms-type">
		<xs:sequence>
			<xs:element name="platform" type="auth-platform-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="service-platforms-type">
		<xs:sequence>
			<xs:element name="platform" type="service-platform-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="auth-domains-type">
		<xs:sequence>
			<xs:element name="auth-domain" type="auth-domain-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="auth-platform-type">
		<xs:all>
			<xs:element name="name" type="i18n" minOccurs="1" maxOccurs="1"/>
			<xs:element name="domain-id" type="objectId-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="resource" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="params" type="params-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="auth-domain" type="auth-domain-type" minOccurs="1" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="service-platform-type">
		<xs:all>
			<xs:element name="name" type="i18n" minOccurs="1" maxOccurs="1"/>
			<xs:element name="domain-id" type="objectId-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="resource" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="params" type="params-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="services" type="services-type" minOccurs="1" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="auth-domain-type">
		<xs:all>
			<xs:element name="domain-id" type="objectId-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="piped-storage" type="class-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="storage" type="class-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="domain-resolver" type="class-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="storage-manager" type="class-type" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<!-- maxOperations >= 1000 && <= 1000000 -->
	<xs:simpleType name="max-ops-type">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1000"/>
			<xs:maxInclusive value="1000000"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- threads >= 10 && <= 500 -->
	<xs:simpleType name="threads-type">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="10"/>
			<xs:maxInclusive value="500"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- maxLife >= 8 minutes && <= 1 week -->
	<xs:simpleType name="max-life-type">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="8"/>
			<xs:maxInclusive value="10080"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- key must be 64 characters -->
	<xs:simpleType name="key-type">
		<xs:restriction base="xs:string">
			<xs:length value="64"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="topology-config-type">
		<xs:all>
			<xs:element name="oid-base" type="xs:integer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="auth-tier" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="threadpool" type="threads-type" default="20" minOccurs="0" maxOccurs="1"/>
						<xs:element name="max-operations" type="max-ops-type" default="100000" minOccurs="0" maxOccurs="1"/>
						<xs:element name="logging" type="logging-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="nodes" type="nodes-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="services" type="references-type" minOccurs="0" maxOccurs="1"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="service-tier" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="threadpool" type="threads-type" default="20" minOccurs="0" maxOccurs="1"/>
						<xs:element name="max-operations" type="max-ops-type" default="100000" minOccurs="0" maxOccurs="1"/>
						<xs:element name="logging" type="logging-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="nodes" type="nodes-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="services" type="references-type" minOccurs="0" maxOccurs="1"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="connection-tier" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="threadpool" type="threads-type" default="20" minOccurs="0" maxOccurs="1"/>
						<xs:element name="max-operations" type="max-ops-type" default="100000" minOccurs="0" maxOccurs="1"/>
						<xs:element name="logging" type="logging-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="nodes" type="nodes-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="services" type="references-type" minOccurs="0" maxOccurs="1"/>
						<xs:element name="servers" type="server-list-type" minOccurs="0" maxOccurs="1"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="authentication-config-type">
		<xs:all>
			<xs:element name="grant-max-lifetime" type="max-life-type" default="1440" maxOccurs="1"/>
			<xs:element name="debug" type="xs:boolean" default="false" maxOccurs="1"/>
			<xs:element name="debug-key" type="key-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="credential" type="credential-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="ct-server-credential" type="credential-type" minOccurs="1" maxOccurs="1"/>
			<xs:element name="domain-credentials" type="credential-list-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="platforms" type="auth-platforms-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="auth-domains" type="auth-domains-type" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="service-config-type">
		<xs:all>
			<xs:element name="platforms" type="service-platforms-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="services" type="services-type" minOccurs="0" maxOccurs="1"/>
			<xs:element name="logging-handlers" type="logging-handlers-type" minOccurs="0" maxOccurs="1"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="three-tier-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="authentication-config" type="authentication-config-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="service-config" type="service-config-type" minOccurs="0" maxOccurs="1"/>
				<xs:element name="topology-config" type="topology-config-type" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" default="1.0"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== joshpitts-okta/developer/interfaceRepository/config/etc/opt/enc/ttc/common/auth.config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<three-tier-config
    xmlns="http://emit-networking.org/schema/ttc/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://emit-networking.org/schema/ttc/config http://emit-networking.org/schema/ttc/config/ttc.config.xsd" version="1.0">
    <authentication-config>
        <grant-max-lifetime>1440</grant-max-lifetime>
        <debug>false</debug>
        <!--debug-key>0000000000000000000000000000000000000000000000000000000000000000</debug-key-->
        <credential ref="router.cluster.pesdca.com"/>
        <ct-server-credential ref="ctrouter.cluster.pesdca.com"/>

        <platforms>
            <platform>
                <name>Residential Platform</name>
                <domain-id>[6:res.pesdca.com]</domain-id>
                <resource>file:///opt/enc/res/pgsql/spring/res.auth.spring.xml</resource>
                <params>
                    <param name="res.user">res_user</param>
                    <param name="res.password">res_user</param>
                    <param name="res.host">engorcl</param>
                    <param name="res.port">5433</param>
                    <param name="res.database-name">res</param>
                </params>

                <auth-domain>
                    <piped-storage name="pipedStorage">
                        <resource>file:///opt/enc/res/pgsql/spring/res.piped-storage.spring.xml</resource>
                    </piped-storage>

                    <storage name="org.emitdo.as.postgres.PostgresStorage">
                        <params>
                            <param name="user">res_user</param>
                            <param name="password">res_user</param>
                            <param name="host">engorcl</param>
                            <param name="port">5433</param>
                            <param name="database-name">asdb</param>
                        </params>
                    </storage> 
                </auth-domain>
            </platform>

            <platform>
                <name>Battery Platform</name>
                <domain-id>[6:battery.pewla.com]</domain-id>
                <resource>file:///opt/enc/battery/pgsql/spring/battery.auth.spring.xml</resource>
                <params>
                    <param name="battery.user">battery_platform_manager</param>
                    <param name="battery.password">battery_platform_manager</param>
                    <param name="battery.host">engorcl</param>
                    <param name="battery.port">5433</param>
                    <param name="battery.database-name">battery</param>

                    <param name="battery.slow.user">battery_platform_manager</param>
                    <param name="battery.slow.password">battery_platform_manager</param>
                    <param name="battery.slow.host">engorcl</param>
                    <param name="battery.slow.port">5433</param>
                    <param name="battery.slow.database-name">battery</param>
                </params>

                <auth-domain>
                    <!--piped-storage name="pipedStorage">
                        <resource>file:///opt/enc/battery/pgsql/spring/battery.piped-storage.spring.xml</resource>
                    </piped-storage-->

                    <storage name="org.emitdo.as.postgres.PostgresStorage">
                        <params>
                            <param name="user">battery_user</param>
                            <param name="password">battery_user</param>
                            <param name="host">engorcl</param>
                            <param name="port">5433</param>
                            <param name="database-name">asdb</param>
                        </params>
                    </storage> 
                </auth-domain>
            </platform>

            <!--platform>
                <name>Ancillary Platform</name>
                <domain-id>[6:ancillary.pewla.com]</domain-id>
                <resource>file:///opt/enc/res/pgsql/spring/ancillary.auth.spring.xml</resource>
                <params>
                    <param name="res.user">ancillary_user</param>
                    <param name="res.password">ancillary_user</param>
                    <param name="res.host">engorcl</param>
                    <param name="res.port">5433</param>
                    <param name="res.database-name">ancillary1</param>
                </params>

                <auth-domain>
                    <piped-storage name="pipedStorage">
                        <resource>file:///opt/enc/res/pgsql/spring/ancillary.piped-storage.spring.xml</resource>
                    </piped-storage>

                    <storage name="org.emitdo.as.postgres.PostgresStorage">
                        <params>
                            <param name="user">ancillary_user</param>
                            <param name="password">ancillary_user</param>
                            <param name="host">engorcl</param>
                            <param name="port">5433</param>
                            <param name="database-name">as1</param>
                        </params>
                    </storage> 
                </auth-domain>
            </platform-->
        </platforms>

        <auth-domains>
            <auth-domain>
                <domain-id>[6:cluster.pesdca.com]</domain-id>
                <piped-storage name="org.emitdo.app.as.storage.RouterPipedStorage"/>
                <domain-resolver name="org.emitdo.as.postgres.PostgresDomainResolver"/>
                <storage name="org.emitdo.as.postgres.PostgresStorage">
                    <params>
                        <param name="user">cluster_user</param>
                        <param name="password">cluster_user</param>
                        <param name="host">engorcl</param>
                        <param name="port">5433</param>
                        <param name="database-name">asdb</param>
                    </params>
                </storage>
            </auth-domain>
                  
            <auth-domain>
                <domain-id>[6:factory.pesdca.com]</domain-id>
                <storage name="org.emitdo.as.postgres.PostgresStorage">
                    <params>
                        <param name="user">factory_user</param>
                        <param name="password">factory_user</param>
                        <param name="host">engorcl</param>
                        <param name="port">5433</param>
                        <param name="database-name">asdb</param>
                    </params>
                </storage>
            </auth-domain>

            <!--auth-domain>
                <domain-id>[6:battery.pewla.com]</domain-id>
                <storage name="org.emitdo.as.postgres.PostgresStorage">
                    <params>
                        <param name="user">battery_user</param>
                        <param name="password">battery_user</param>
                        <param name="host">engorcl</param>
                        <param name="port">5433</param>
                        <param name="database-name">as1</param>
                    </params>
                </storage>
            </auth-domain-->

            <auth-domain>
                <domain-id>[6:ancillary.pewla.com]</domain-id>
                <storage name="org.emitdo.as.postgres.PostgresStorage">
                    <params>
                        <param name="user">ancillary_user</param>
                        <param name="password">ancillary_user</param>
                        <param name="host">engorcl</param>
                        <param name="port">5433</param>
                        <param name="database-name">asdb</param>
                    </params>
                </storage>
            </auth-domain>

        </auth-domains>
    </authentication-config>
</three-tier-config>

=== joshpitts-okta/developer/interfaceRepository/config/etc/opt/enc/ttc/common/topology.config.double.column.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<three-tier-config
    xmlns="http://emit-networking.org/schema/ttc/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://emit-networking.org/schema/ttc/config http://emit-networking.org/schema/ttc/config/ttc.config.xsd" version="1.0">
    <topology-config>
        <oid-base>16383</oid-base>
<!-- Authentication Tier section -->
        <auth-tier>
            <max-operations>500000</max-operations>
            <threadpool>24</threadpool>
            <logging level="debug"/>
            <nodes>
                <node as-id="0" id="0">
                    <name>Auth Node 1</name>
                    <address>127.0.0.1:18567</address>
                </node>
                <node as-id="1" id="1">
                    <name>Auth Node 2</name>
                    <address>127.0.0.1:28567</address>
                </node>
            </nodes>
        </auth-tier>
<!-- Service Tier section -->
        <service-tier>
            <max-operations>500000</max-operations>
            <threadpool>256</threadpool>
            <logging level="debug"/>
            <nodes>
                <node id="2">
                    <name>Service Node 1</name>
                    <address>127.0.0.1:18568</address>
                </node>
                <node id="3">
                    <name>Service Node 2</name>
                    <address>127.0.0.1:28568</address>
                </node>
            </nodes>
            <services>
                <service include="0"/>
                <service include="1"/>
                <service include="2"/>
                <service include="3"/>
                <service include="4"/>
                <service include="5"/>
                <service include="6"/>
                <service include="7"/>
                <service include="8"/>
                <service include="9"/>
                <service include="10"/>
                <service include="11"/>
            </services>
        </service-tier>
<!-- Connection Tier section -->
        <connection-tier>
            <max-operations>500000</max-operations>
            <threadpool>24</threadpool>
            <logging level="debug"/>
            <nodes>
                <node id="4">
                    <name>Conn Node 1</name>
                    <address>127.0.0.1:13567</address>
                    </node>
                <node id="5">
                    <name>Conn Node 2</name>
                    <address>127.0.0.1:23567</address>
                </node>
            </nodes>
            <servers>
                <datagram id="0">
                    <name>Conn Node Datagram Server</name>
                    <max-connections>1000</max-connections>
                </datagram>
                <stream id="1">
                    <name>Conn Node Stream Server</name>
                    <max-connections>100</max-connections>
                </stream>
                <hub id="2" related-server="0">
                    <name>Conn Node Services Hub</name>
                    <address>[3:servicesHub@res.pesdca.com]</address>
                    <domain-id>[6:res.pesdca.com]</domain-id>
                </hub>
            </servers>
        </connection-tier>
    </topology-config>
</three-tier-config>
